### ISSUE TITLE
Static Images in front page not working

### ISSUE THREAD

**Issue by DefaultSprite** [DefaultSprite/IAB207#2]
For some reason when base.html queries the static folder for the logo it works. Though when it queries the static folder for the images on the front page it doesn't for some reason. The reason why the logo is present may be caused by browser caching as well.

**Comment by michyhems** [comment]
I did notice that, In the my_events page i also pulled an image from that folder and it worked fine. I thought that once we re-tooled the front page to pull from the database it would be fine.

**Comment by DefaultSprite** [comment]
I wouldn't be surprised if I implemented it wrong on my side.

**Comment by michyhems** [comment]
is the navbar on the home page fine on ur end?

**Comment by michyhems** [comment]
use this in ur href: ../static/image/Studio_Ghibli_Logo.jpg

**Comment by DefaultSprite** [comment]
I woke up this morning and saw that the index page is working all of a sudden when I use `{{ url_for('static', filename='image/Studio_Ghibli_Logo.jpg') }}` it just works now with now issue.

![image](https://github.com/DefaultSprite/IAB207/assets/145419744/11588b70-efda-4f28-a3d4-d1d709d4a919)
